services:
  - type: web
    name: lap2devop
    runtime: node
    region: oregon
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
